name: Jeju Sewer Water

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run data fetch script
      run: |
        python crawling.py

    - name: Commit and push changes
      run: |
        git config --local user.email "kimlynnjean@naver.com"
        git config --local user.name "lynnjean"
        git add .
        git commit -m "Add new data"
        git push

